### ISSUE TITLE
DISTAL Library Checklist

### ISSUE THREAD

**Issue by rohany** [rohany/taco#130]
- [x] Test that it works on Sapling in multi-node settings
- [x] Lassen in multi-node settings
- [x] stop printing output from the compilation command to stdout unless asked
- [x] Implement GPU compilation support
- [x] Move runtime library into the DISTAL directory
- [ ] Move runtime library within a namespace
- [x] Move submodule dependencies into a folder called deps
- [ ] Transition compilation tests and generated code tests to use the new API, integrate with gtest
- [ ] Figure out installation details / exports of link and include directories to a target

**Comment by rohany** [comment]
Multi-node is working once https://gitlab.com/StanfordLegion/legion/-/merge_requests/519 lands and we upstream legion.
