### ISSUE TITLE
Legion Issues Tracker

### ISSUE THREAD

**Issue by rohany** [rohany/taco#27]
A meta issue for me to track all of the Legion issues that I'm blocked on.

# Legion

These are bugs blocking either implementation of benchmarks that I want to write, or evaluation of benchmarks that I already have.

## GASNetEx
- [x] Invalid gather from GPU device memory https://github.com/StanfordLegion/legion/issues/1122 -- hard blocker. Shows up in MTTKRP, COSMA. Running with `-gex:bindcuda 0` gets rid of the segfault, but comes at an unacceptable performance hit (basically puts us back at gasnet1 speeds).
- [x] Crashes when running at high node counts https://github.com/StanfordLegion/legion/issues/1118 (blocks large multi-GPU GEMM runs). Even with `-gex:batch 0` I see some errors, and performance with `-gex:batch 0` is noticeably worse.
- [ ] 2D Gathers with Gex https://github.com/StanfordLegion/realm/issues/91. I believe that multi-node adapt benchmark needs this. I think that this will also improve performance of the 2d algorithms on rectangular node counts.

## Core Legion
- [x] Assertion failure around futures / hangs with mttkrp + futures https://github.com/StanfordLegion/legion/issues/1123. (TODO (rohany): When this is fixed, pull control replication to get the fix for memory corruption around instance reuse).
- [x] Slow CPU fills https://github.com/StanfordLegion/realm/issues/90
- [x] Memory corruption around instance reuse https://github.com/StanfordLegion/legion/issues/1108 (sean has a patch for this in progress)
- [ ] Collective instances https://github.com/StanfordLegion/legion/issues/546. These are necessary for algorithms which fully replicate a (small) single region among all GPUs. We have a hacky workaround for now, but it isn't great. Collective instances will also be needed for algorithms (like mttkrp) that replicate a portion of a region onto many nodes (https://github.com/StanfordLegion/legion/issues/1125).
- [x] Another hang around future maps: https://github.com/StanfordLegion/legion/issues/1145

## Feature Requests
- [ ] Virtual mappings for reduction instances https://github.com/StanfordLegion/legion/issues/1119. Without this, we can't feasibly implement hierarchical distribution with algorithms that use reductions at the leaves (COSMA, Johnson, Solomonik). This does not look like it's going to be implemented by the PLDI deadline, so I should pivot things to performing flat decompositions over each GPU.

# Legate

I'd like to benchmark against Legate, but there are some errors here blocking me from doing so.

- [ ] Sharding functor output error https://github.com/nv-legate/legate.numpy/issues/53
- [ ] Bad instance mapping leading to OOMs (I don't have an issue for this, but Manolis said he is looking into it).

**Comment by rohany** [comment]
Closing as this was relevant to the PLDI deadline, which has passed.
